### ISSUE TITLE
apollo-link@1.0.3 fails with `nextLink.execute is not a function`

### ISSUE THREAD

**Issue by tdeekens** [apollographql/apollo-link#258]
**Intended outcome:**

When setting up apollo-link in a way such as

```js
const httpLink = createHttpLink({
  uri: `${window.app.protocol}://${window.app.host}/graphql`,
});

// we define the other middlewares

const link = ApolloLink.from([headerMiddlewareLink, errorLink, httpLink]);

const client = new ApolloClient({
  link,
  cache: new InMemoryCache({
    dataIdFromObject: object => object.id,
  }),
});
```

we should be able to use Apollo

```jsx
<ApolloProvider client={client}>
   <App />
</ApolloProvider>
```

**Actual outcome:**

We get an error

<img width="436" alt="screen shot 2017-11-17 at 13 56 59" src="https://user-images.githubusercontent.com/1877073/32948350-3952e468-cb9f-11e7-8370-5c845d605a63.png">

**How to reproduce the issue:**

Using the following dependencies seems to reproduce the issue for us

```json
"apollo-link": "^1.0.3",
"apollo-link-error": "^1.0.1",
"apollo-link-http": "^1.2.0",
```

When downgrading `apollo-link` to `1.0.0` the issue resolves for us.

**Comment by Kaihuang724** [comment]
I have the same issue, but downgrading `apollo-link` to `1.0.0` didn't fix the problem for me.

What version is your `apollo-client`? I need to get this problem fixed for now to continue development.

Thanks for your help, @tdeekens

**Comment by tdeekens** [comment]
`apollo-client` is at `2.0.2`.

**Comment by jbaxleyiii** [comment]
@tdeekens how are you importing `ApolloLink`?

**Comment by jbaxleyiii** [comment]
hmm, can you create a reproduction for me to take a look at?

**Comment by Kaihuang724** [comment]
Downgrading `apollo-client` to `2.0.2` worked for me.

**Comment by tdeekens** [comment]
I can report that this was resolved with later versions and combinations of things. Maybe this is worth closing whenever others have checked.

**Comment by Kaihuang724** [comment]
@tdeekens How did you resolve this? I just opened up the project again with `apollo-link: 1.2.1` and `apollo-client: 2.2.5` but still getting same error.

**Comment by tdeekens** [comment]
We upgraded to another version combination and things were solved for us.

**Comment by Kaihuang724** [comment]
Got it - would you be able to let me know which version combination you have to get it working? Mine's still not working with the latest versions of everything.

I appreicate your help.
