### ISSUE TITLE
Console link doesn't work with subscriptions (Error: iterator.next is not a function)

### ISSUE THREAD

**Issue by schickling** [apollographql/apollo-link#386]
**Intended outcome:**

The console link (taken from the [Link docs](https://www.apollographql.com/docs/link/stateless.html#stateless)) should work in combination with subscriptions.

**Actual outcome:**

I'm seeing this error when subscribing `Error: iterator.next is not a function`

This is how the links are composed: https://github.com/graphcool/graphcool-binding/blob/80584afc36c528ab38a2dad3ab6ac8fee4761b31/src/link.ts#L68

My suspicion is that it's either

1. a bug in `apollo-link`
2. or we need to handle subscriptions differently in the `graphql-binding` ([see relevant code](https://github.com/graphcool/graphql-binding/blob/master/src/handler.ts#L59-L85))

**How to reproduce the issue:**

Set up [this repo](https://github.com/graphcool/graphcool-server-example/) and set the `debug: true` flag when initializing `new Graphcool` in `src/index.ts`.

**Comment by schickling** [comment]
@evans is this now fixed?

**Comment by evans** [comment]
Yes it appears to be fixed with the most recent release: https://codesandbox.io/s/nw7v4vxzll

**Comment by evans** [comment]
@schickling Ah really sorry I saw the `prisma-bindings` issue was fixed, so I assumed this was as well. I realize there might still be issues here, so I'll reopen.

I have https://codesandbox.io/s/0pjx39r7m0 setup and don't have a good endpoint to hit. Do have a reliable source of subscription events?

**Comment by srtucker22** [comment]
Hey, @evans.

I think this is still an issue. 

Here's an easy way to replicate it:
Clone the [chatty tutorial](https://github.com/srtucker22/chatty/) (WhatsApp clone tut) -- you can even go to the commit step https://github.com/srtucker22/chatty/commit/7b403559b5244409763e218d2d99d6c5cdc5bb1b where we add our first subscription

This code should be pretty easy to spin up -- just `yarn` at root and at `/client` (package installs separate for server and client) `yarn start` at root to start server and `react-native run-ios` at `/client` to start RN client.

All should go well and you'll have a working app with a subscription for new chat messages when you enter the Messages view.

If you comment out the [`errorLink`](https://github.com/srtucker22/chatty/blob/master/client/src/app.js#L127) in `/client/src/app.js`, we get `observer.map` is not a function when links are expecting an observer response from subscription init.

Is this a helpful way to reproduce?
